name: smtc_windows
description: Windows `SystemMediaTransportControls` implementation for Flutter giving access to Windows OS Media Control applet.
version: 0.1.2
homepage: https://github.com/KRTirtho/smtc_windows
repository: https://github.com/KRTirtho/smtc_windows/tree/main/packages/smtc_windows

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1
  flutter_rust_bridge: ^1.82.6
  plugin_platform_interface: ^2.0.2
  meta: ^1.8.0
  uuid: ^4.4.0

dev_dependencies:
  ffigen: ^9.0.1
  lints: ^2.0.0
  test: ^1.21.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      windows:
        ffiPlugin: true
