[package]
name = "{{name.snakeCase()}}"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.82.*"

[dependencies]
flutter_rust_bridge = "1.82.*"
